name: Build and Push to Heroku

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to Heroku Container Registry
      uses: docker/login-action@v1 
      with:
        registry: registry.heroku.com
        username: _
        password: ${{ secrets.HEROKU_API_KEY }}
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: registry.heroku.com/example-frontend-dwd/web
